### ISSUE TITLE
Console Widget crashes when asking autocompletions

### ISSUE THREAD

**Issue by hzyrc6011** [jupyter/qtconsole#440] opened 2020-09-03 03:33 UTC
version:4.7.6
platform:python3.8,linux,amd64

Hello Sir/Madam:
I am sincerely appreciate of your great work on this. However when I start  the code shown in your demostration(https://github.com/jupyter/qtconsole/blob/master/examples/embed_qtconsole.py),I typed an 'a' and then tried to press 'tab' to call for autocompletion(just imitate some 'unwelcomed' users). However the program instantly crashed with the error shown below:

``` bash
Traceback (most recent call last):
  File "/home/hzy/anaconda3/envs/pyminer/lib/python3.8/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/hzy/anaconda3/envs/pyminer/lib/python3.8/site-packages/qtconsole/jupyter_widget.py", line 178, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "/home/hzy/anaconda3/envs/pyminer/lib/python3.8/site-packages/qtconsole/console_widget.py", line 1053, in _complete_with_items
    self._completion_widget.show_items(cursor, items,
  File "/home/hzy/anaconda3/envs/pyminer/lib/python3.8/site-packages/qtconsole/completion_html.py", line 313, in show_items
    displaywidth = int(max(10, (width / char_width) - 1))
ZeroDivisionError: float division by zero

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

``` 
Maybe there are some try-catches or value checkings are missing in the files above.
Thankyou!

**Comment by ccordoba12** [comment] 2020-09-03 03:48
Duplicate of #437.

**Closed by ccordoba12** 2020-09-03 03:48 UTC
