### ISSUE TITLE
Carriage Return Inconsistency

### ISSUE THREAD

**Issue by poipoi300** [jupyter/qtconsole#553] opened 2022-07-06 15:54 UTC
# Context
I was writing a simple progress indicator for use internally in Spyder and found out that carriage returns don't always work, meaning that trying to print over lines in the console sometimes appends the new text instead. When I discovered this, I took out Spyder from the equation and tested directly in Qt Console. I experienced the same problem. I then updated Qt Console to the latest version (5.3.1), and the problem got better, however it still occurred and a new issue popped up where text would be updated much less often (sometimes not at all until the final output). I have tested this in the windows command line, and it behaves exactly as expected. I have tested this on 2 systems, both running windows (10 and 11).

### Expected behavior
Carriage returns always return the cursor to the start of the line and the console's output is updated for each new print.
### Actual behavior
Carriage returns are sometimes not taken into account, and text is appended when it should not be. The console's output updates are also delayed.
### Reproducing the behavior
```py
# If this snippet does not show issues, run it more times or add iterations.

for i in range(1000000):
    print(f'{i} ', end = '\r') # Flushing makes the issue worse 

# Example output:
# 999999 142189 773780
```

#### IPython.sys_info() output
```js
{'commit_hash': 'e321e760a',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\IPython',
 'ipython_version': '7.31.1',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.22000-SP0',
 'sys_executable': 'C:\\ProgramData\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit '
                '(AMD64)]'}
```

**Comment by ccordoba12** [comment] 2022-07-07 02:27
Hey @poipoi300, thanks for reporting. This is basically a duplicate of issue #350.

It'd be great if you could give us a hand to improve our ANSI pre-processor. On that issue you can find the minimal info to do it, in case you are interested.

**Closed by ccordoba12** 2022-07-07 02:27 UTC
