### ISSUE TITLE
JupyterConsole.svg icon file missing in qtconsole 4.0.0?

### ISSUE THREAD

**Issue by lebedov** [jupyter/qtconsole#39] opened 2015-08-12 19:08 UTC
When I run qtconsole 4.0.0 (installed via pip in a conda environment), the following message is printed:

```
Cannot open file '/home/lev/Work/miniconda/envs/DEFAULT/lib/python2.7/site-packages/qtconsole/resources/icon/JupyterConsole.svg', because: No such file or directory
```

**Comment by lebedov** [comment] 2015-08-13 02:20
The icon doesn't appear to be in the whl or tar.gz files on pypi. Shouldn't the icon file be listed in MANIFEST.in?

**Comment by minrk** [comment] 2015-08-13 04:16
It was added to package_data in #37. This is a duplicate of #36.

**Closed by minrk** 2015-08-13 04:16 UTC
