### ISSUE TITLE
C-a (jump to beginning of line)

### ISSUE THREAD

**Issue by temok-mx** [jupyter/qtconsole#207] opened 2017-04-10 20:35 UTC
Dear All, on `QtConsole 4.3.0` the command C-a (i.e. Control-a) moves the cursor  between the 1st and 2nd characters of a non-empty line. This is in contrast with Emacs, where this command moves the pointer to the very beginning of line. Is this the intention on Qtconsole?
Cheers, Temok

**Comment by temok-mx** [comment] 2017-04-10 21:18
p.s. Indeed, on `QtConsole 4.3.0` one needs a double `C-a` to move the cursor to the beginning of a line.

**Comment by ccordoba12** [comment] 2017-04-10 23:26
> on QtConsole 4.3.0 the command C-a (i.e. Control-a) moves the cursor between the 1st and 2nd characters of a non-empty line

What do you mean exactly?

**Comment by temok-mx** [comment] 2017-04-11 00:01
Hi @ccordoba12 , Suppose that on qtconsole the cursor is before letter "y" of the line`import numpy as np`. On Emacs, and most Unix/Linux applications, pressing `Control-a` will move the cursor before letter "i", the very beginning of that line. 

Turns out that on qtconsole `control-a` moves the cursor before the first "m" of that line. If I want to go exactly to the beginning the line, then I need to press twice that command, i.e. "control-a, control-a". Other commands, like "control-e" work as expected (in this case the cursor jumps to the end of line). Cheers, Temok

**Comment by ccordoba12** [comment] 2017-04-11 00:05
This certainly sounds like a bug. Thanks for reporting it.

**Comment by ccordoba12** [comment] 2017-04-11 00:07
@andfoy, please work on this one.

**Comment by andfoy** [comment] 2017-04-16 02:24
I can't reproduce this error on 4.4.0, pressing Ctrl+A actually sets cursor position at beginning

**Comment by wmvanvliet** [comment] 2017-05-12 08:00
"The beginning of the line" translates to "wherever QtConsole thinks the prompt ends". As of 4.3.0, the latter is tracked by a "prompt cursor". It can be that this cursor gets out of sync at some point. We do some hairy +1, -1 gimmickry from time to time with this cursor, so an off-by-one error seems plausible. It's not going to be fun having to track it down though...

If there's a way to reliably reproduce this bug, then it would be much easier to solve.

**Comment by wmvanvliet** [comment] 2017-05-29 05:59
I can reproduce this, but not reliably.

**Comment by temok-mx** [comment] 2017-05-29 14:20
Hi @wmvanvliet, the same for me. I originally started this thread, then days later I noticed the bug was gone. I wonder if it would be related to the imported modules I was working on that day.
Cheers,
Temok

**Comment by SebastianSchafer** [comment] 2017-07-31 23:32
Noticed this issue in spyder using qtsonsole 4.3.0. Interestingly, issue disappeared within a running spyder/IPython console session, i.e. while initially I needed 2x 'ctr+a' or 'home', after a while (Without starting a new console/kernel), I can't reproduce it, the cursor always ends up at the first position. I'm almost certain that I did not import any additional modules in the meantime. This is Py3.6.1 on Win7, using conda packages.

**Comment by wmvanvliet** [comment] 2017-08-01 08:27
It's unlikely this is caused by importing modules. It looks like the `prompt_cursor` is misaligned at some point. Then, after re-drawing the prompt it will be reset and the issue disappeared. I'll keep a lookout for a way to reliably reproduce this so I can debug it.

**Comment by talkaminker** [comment] 2017-09-12 17:19
I have the same issue with qtconsole 4.3.1 but not with 4.2.1

**Comment by EhsanKia** [comment] 2018-10-07 02:51
It might to have to do with your prompt number that increments with every command. When it goes from N digits to N+1 digits, your cursor gets misaligned. Still trying to find reliable repro steps, but I hit this bug regularly.

**Comment by wmvanvliet** [comment] 2018-10-07 10:33
That is a valuable hint, thanks!

**Comment by EhsanKia** [comment] 2018-10-07 21:57
Have some free time this weekend and decided to dig into this issue. I'll be writing out my findings as I go along here, so even if I don't find a fix, hopefully it can help anyone looking at this bug in the future.

The best candidate file for where this could be happening is [console_widget.py](https://github.com/jupyter/qtconsole/blob/master/qtconsole/console_widget.py), as it looks to have all methods related to cursor position. More specifically for this bug, I would guess inside [`QtCore.Qt.Key_Home`](https://github.com/jupyter/qtconsole/blob/master/qtconsole/console_widget.py#L1409-L1427). From reports, it seems to have broken between 4.2.1 (March 30, 2016) and 4.3.1 (August 12, 2017).

Looking at changes around that time range, these jumped to my attention:
[Home key event updated](https://github.com/jupyter/qtconsole/commit/a4f409ba6abd9c56b25fd17a670af4fe5de8e7ca)  (4.3.0)
[Alternate between start of line and start of text](https://github.com/jupyter/qtconsole/commit/657af866db1c93950b4bfbe29b1c666c4b2f1c56) (4.3.0)
[Home key event updated.](https://github.com/jupyter/qtconsole/commit/4fafcd99a42aea59cf96c95448ee06eb5efd3f12) (4.3.0)
[Propertly keep track of prompt position](https://github.com/jupyter/qtconsole/commit/7bea0a3368cc5516ef7034d1e379a46fad9b45c8) (4.3.0)
[Restore cursor position move before inserting prompt](https://github.com/jupyter/qtconsole/commit/5d985c40954b354c66f8f92213a6f62c19ad9d83) (4.3.1)
[Fix _get_leading_spaces to check first line vs. continuation](https://github.com/jupyter/qtconsole/commit/afae3f51835a471067e558cee8c72586ff357edc) (4.4.0)

The last commit is outside the range, but since I'm running 4.3.1, I'm curious if that already solves the bug. So I just upgraded to 4.4.1 and will see if I can still reproduce this.

**Comment by ccordoba12** [comment] 2019-05-23 11:59
@EhsanKia, so is this fixed in 4.4.0+?

**Comment by EhsanKia** [comment] 2019-05-23 20:39
I have personally not run into this issue since, so it may be fair to mark it as fixed. I'll return here and update if I run into it again on 4.4.0+

**Comment by ccordoba12** [comment] 2019-05-24 09:14
Ok, thanks for the confirmation. Closing this for now.

**Closed by ccordoba12** 2019-05-24 09:14 UTC
Labels: bug
