### ISSUE TITLE
Kernel is taking too long to finish

### ISSUE THREAD

**Issue by skualos** [jupyter/qtconsole#220] opened 2017-06-16 02:45 UTC
It takes around  10 seconds to close the Jupyter Qt Console window
Debug gives the following messages:

[JupyterQtConsoleApp] Kernel is taking too long to finish, killing
[JupyterQtConsoleApp] shutdown: {'restart': False, 'status': 'ok'}
After Qt shutting down, terminal stays hanged up (has to stop it with Ctrl+C)

Ubuntu 16.04
Jupyter QtConsole 4.3.0
Python 3.5.2
IPython 6.1.0

**Comment by wmvanvliet** [comment] 2017-06-19 06:25
Do you have this consistently? Also when just starting QtConsole and immediately closing it?

**Comment by skualos** [comment] 2017-06-19 07:09
Hi. Yes, consistently, and also when just starting and closing QtConsole. Let me know if I can help.

**Comment by wmvanvliet** [comment] 2017-06-19 07:26
When re-creating your environment, my QtConsole gives the following error:

    python: No module named ipykernel_launcher

are you also getting that?

**Comment by skualos** [comment] 2017-06-19 08:04
No, I don't get this error. This is what the Terminal debug gives me after finishing searching for config files:
```
[JupyterQtConsoleApp] Connection File not found: /run/user/1000/jupyter/kernel-13237.json
[JupyterQtConsoleApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[JupyterQtConsoleApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel_launcher', '-f', '/run/user/1000/jupyter/kernel-13237.json']
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:49568
[JupyterQtConsoleApp] connecting shell channel to tcp://127.0.0.1:52258
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:52258
[JupyterQtConsoleApp] connecting iopub channel to tcp://127.0.0.1:46825
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:46825
[JupyterQtConsoleApp] connecting stdin channel to tcp://127.0.0.1:43528
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:43528
[JupyterQtConsoleApp] connecting heartbeat channel to tcp://127.0.0.1:43649
[JupyterQtConsoleApp] stream: {'text': 'Using matplotlib backend: Qt4Agg\n', 'name': 'stdout'}
[JupyterQtConsoleApp] Received history reply with 1000 entries
```

**Comment by wmvanvliet** [comment] 2017-06-20 12:03
Ok, I can reproduce this now. Thanks for reporting.

**Comment by wmvanvliet** [comment] 2017-06-20 13:24
This seems to be something deep inside the IPython kernel. The kernel manager is requesting the kernel to shut down. I've traces the messages and the kernel is receiving the message, but somehow fails to actually stop.

**Comment by skualos** [comment] 2017-06-22 00:43
Let me know if I can help in any other way.

**Comment by skualos** [comment] 2017-06-23 00:15
Problem seems to be gone after having deleted ~/.ipython and ~/.jupyter folders.

**Comment by ccordoba12** [comment] 2017-06-23 00:16
Great!

**Closed by ccordoba12** 2017-06-23 00:16 UTC
