### ISSUE TITLE
qtconsole==5.0.0 breaks python 2.7 environments

### ISSUE THREAD

**Issue by Freyja-Folkvangr** [jupyter/qtconsole#456] opened 2020-11-24 14:00 UTC
Hi, 
Jupyter (along with other packages) requires qtconsole, they do not specify any version so by default it installs the latest version.

qtconsole version 5.0.0 breaks python 2.7 environments when installing requirements.

I know python2.7 is deprecating, so we're currently migrating at the company but it is not done yet.

**We had this error on our CI environment**

```
    Collecting qtconsole

    Downloading qtconsole-5.0.0.tar.gz (424 kB)

    ERROR: Command errored out with exit status 1:

    Complete output (6 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-p3ALmm/qtconsole/setup.py", line 18

        print(error, file=sys.stderr)

    SyntaxError: invalid syntax

    ----------------------------------------

    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ccordoba12** [comment] 2020-11-24 17:08
Duplicate of #455

**Closed by ccordoba12** 2020-11-24 17:08 UTC
