### ISSUE TITLE
Pressing "Tab" leads to ZeroDivisionError (qtconsole==4.7.6)

### ISSUE THREAD

**Issue by 3fon3fonov** [jupyter/qtconsole#439] opened 2020-08-30 10:40 UTC
As the title points, trying to automatically fill in the rest of a variable name leads to:

```
<class 'ZeroDivisionError'> float division by zero <traceback object at 0x7fad83942500>
===== 2020.08.30 12:08:27 =====
Traceback (most recent call last):
  File "/home/trifonov/.local/lib/python3.8/site-packages/qtconsole-4.7.6-py3.8.egg/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/trifonov/.local/lib/python3.8/site-packages/qtconsole-4.7.6-py3.8.egg/qtconsole/jupyter_widget.py", line 178, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "/home/trifonov/.local/lib/python3.8/site-packages/qtconsole-4.7.6-py3.8.egg/qtconsole/console_widget.py", line 1053, in _complete_with_items
    self._completion_widget.show_items(cursor, items,
  File "/home/trifonov/.local/lib/python3.8/site-packages/qtconsole-4.7.6-py3.8.egg/qtconsole/completion_html.py", line 313, in show_items
    displaywidth = int(max(10, (width / char_width) - 1))
ZeroDivisionError: float division by zero

```

This crashes my GUI ! Please suggest a general fix to this.

**Comment by char101** [comment] 2020-08-31 15:02
It is the same problem as decribed here https://github.com/jupyter/qtconsole/issues/437#issuecomment-682471961

**Comment by 3fon3fonov** [comment] 2020-09-02 13:47
I see. I would be very happy to close this Issue, once the bug is fixed. Hopefully, a new release will be pushed to pypi soon.

**Comment by ccordoba12** [comment] 2020-09-02 17:31
Closing as a duplicate of #437.

**Closed by ccordoba12** 2020-09-02 17:31 UTC
