### ISSUE TITLE
syntax style problem

### ISSUE THREAD

**Issue by hemoumouda** [jupyter/qtconsole#549] opened 2022-06-26 07:08 UTC
When I was using the qtconsole(version is 5.3.1), I found that only the **first line of the multi-line code can display the syntax style.**
![screenshot](https://user-images.githubusercontent.com/102949335/176076199-4c18af13-12f3-48c8-a5ce-cd43c7453748.png)
I hope it gets fixed soon, thanks a lot!

**Comment by hemoumouda** [comment] 2022-06-26 07:16
![img](https://user-images.githubusercontent.com/102949335/175803707-1228832c-e618-45e7-bf97-160d4ccf3094.jpg)

**Comment by dalthviz** [comment] 2022-06-29 15:59
Hi @hemoumouda, just in case, I think this is a duplicate of https://github.com/jupyter/qtconsole/issues/546 

If that is the case, a fix will be available in the next release (5.3.2): https://github.com/jupyter/qtconsole/pull/547

**Comment by hemoumouda** [comment] 2022-06-30 00:00
@dalthviz Thanks!

**Closed** 2022-06-30 00:01 UTC
