### ISSUE TITLE
QtConsole Tabs: title and motion

### ISSUE THREAD

**Issue by temok-mx** [jupyter/qtconsole#122] opened 2016-04-25 20:03 UTC
Dear Developers,

I wonder if the QtConsole could have
-- a shortcut to move between different tabs, and
-- a command to set the title / color of the current tab.

Currently we need to use the mouse to move around 
and all tabs have titles that  makes it hard to remember 
what we are doing therein (`kernel 1`, `kernel 2`, ...).

Cheers,
Temok

**Comment by wmvanvliet** [comment] 2016-10-07 07:58
CTRL+PgUp and CTRL+PgDown move between tabs. This could be extended with a scheme like CTRL+# to jump to a specific tab. And I agree that setting the title and even color of a tab would be welcome.

**Comment by tmr232** [comment] 2016-10-09 14:20
This seems to be a duplicate of #100

**Comment by wmvanvliet** [comment] 2016-10-10 06:43
More or less, although this is about setting the title of the tabs, not the window.

**Comment by tmr232** [comment] 2016-10-10 07:52
Hmm, you're right.

**Closed** 2016-10-13 08:14 UTC
